load("//tools:apollo_package.bzl", "apollo_package")
load("//tools/proto:proto.bzl", "proto_library")

package(default_visibility = ["//visibility:public"])

proto_library(
    name = "slam_gmapping_conf_proto",
    srcs = ["slam_gmapping_conf.proto"],
)


apollo_package()
